//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentPlanner {
    
    
    public partial class TP_TermsAndConditions {

        protected global::System.Web.UI.WebControls.PlaceHolder DBDataPlaceHolder;
		protected global::System.Web.UI.WebControls.PlaceHolder DBDataPlaceHolder1;
		protected global::System.Web.UI.WebControls.PlaceHolder phPlayers; 
		protected global::System.Web.UI.WebControls.Label lblPlayerCount;	

		//Tournament Summary Fields
		protected global::System.Web.UI.WebControls.Label lblTournamentName;
		protected global::System.Web.UI.WebControls.Label lblEntryOpenDate;	
		protected global::System.Web.UI.WebControls.Label lblEntryClosesDate;
		protected global::System.Web.UI.WebControls.Label lblEntryWithdrawalDate;
		protected global::System.Web.UI.WebControls.Label lblTournamentDuration;
		protected global::System.Web.UI.WebControls.Label lblTournamentOrganisation;
		protected global::System.Web.UI.WebControls.Label lblTournamentVenue;
		protected global::System.Web.UI.WebControls.Label lblTournamentContacts;
		protected global::System.Web.UI.WebControls.Label lblLocationAddress;
		protected global::System.Web.UI.WebControls.LinkButton lbtnRegistrationForm;
		protected global::System.Web.UI.WebControls.DataGrid dgPlayerParticilationList;	

		protected global::System.Web.UI.WebControls.CheckBox chkbAgree;	
		protected global::System.Web.UI.WebControls.Button btnPayment;	
				
    }
}
