//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentPlanner {
    
    
    public partial class TP_UmpireView {
		
		//Fields to show error messages on the page
		protected global::System.Web.UI.WebControls.Panel pnlErrorMsg;
		protected global::System.Web.UI.WebControls.Label lblErrorMsg;
		
		//Login
		protected global::System.Web.UI.WebControls.Panel pnlUmpireLogin;
		protected global::System.Web.UI.WebControls.TextBox txtTournamentCode;
		protected global::System.Web.UI.WebControls.TextBox txtUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtOTPCode;
		protected global::System.Web.UI.WebControls.TextBox txtCaptchaCode;
		
		//Match Kickoff
		protected global::System.Web.UI.WebControls.TextBox txtUmpireCode;
		protected global::System.Web.UI.WebControls.TextBox txtUmpireName;
		protected global::System.Web.UI.WebControls.TextBox txtMatchLocation;
		protected global::System.Web.UI.WebControls.DropDownList ddlMatchPoints;
		
		protected global::System.Web.UI.WebControls.Panel pnlKickOffMatch;
		protected global::System.Web.UI.WebControls.Panel pnlMatchRound;
		
		//Match List Grid
		protected global::System.Web.UI.WebControls.Panel pnlMatchList;
		protected global::System.Web.UI.WebControls.DataGrid dgMatchList;
		
		
		
		protected global::System.Web.UI.WebControls.Label lblMatchScoreHeading;
		protected global::System.Web.UI.WebControls.Label lblUmpireName;
		protected global::System.Web.UI.WebControls.Label lblMatchLocation;
		
		protected global::System.Web.UI.WebControls.Label lblMatchID;
		protected global::System.Web.UI.WebControls.Label lblMatchStatus;
		protected global::System.Web.UI.WebControls.Label lblNoOfSetsPoints;
		protected global::System.Web.UI.WebControls.Label lblMatchDuration;
		
		protected global::System.Web.UI.WebControls.Label lblFirstTeamPlayer;
		protected global::System.Web.UI.WebControls.Label lblSecondTeamPlayer;
		
		protected global::System.Web.UI.WebControls.Label lblFirstSetStartTime;
		protected global::System.Web.UI.WebControls.Label lblSecondSetStartTime;
		protected global::System.Web.UI.WebControls.Label lblThirdSetStartTime;
		
		protected global::System.Web.UI.WebControls.Label lblFirstSetEndTime;
		protected global::System.Web.UI.WebControls.Label lblSecondSetEndTime;
		protected global::System.Web.UI.WebControls.Label lblThirdSetEndTime;
		
		protected global::System.Web.UI.WebControls.Label lblFirstPlayerFirstSetScore;
		protected global::System.Web.UI.WebControls.Label lblFirstPlayerSecondSetScore;
		protected global::System.Web.UI.WebControls.Label lblFirstPlayerThirdSetScore;
		
		protected global::System.Web.UI.WebControls.Label lblSecondPlayerFirstSetScore;
		protected global::System.Web.UI.WebControls.Label lblSecondPlayerSecondSetScore;
		protected global::System.Web.UI.WebControls.Label lblSecondPlayerThirdSetScore;
		
		protected global::System.Web.UI.WebControls.Button btnFirstSetStart;
		protected global::System.Web.UI.WebControls.Button btnSecondSetStart;
		protected global::System.Web.UI.WebControls.Button btnThirdSetStart;
		
		protected global::System.Web.UI.WebControls.Label lblRound1Status;
		protected global::System.Web.UI.WebControls.Label lblRound2Status;
		protected global::System.Web.UI.WebControls.Label lblRound3Status;
		
		protected global::System.Web.UI.WebControls.Button btnIncrementScoreFirstTeam;
		protected global::System.Web.UI.WebControls.Label lblFirstHypenBeteenIncrementDecrementButton;
		protected global::System.Web.UI.WebControls.Button btnDecrementScoreFirstTeam;
		protected global::System.Web.UI.WebControls.Button btnIncrementScoreSecondTeam;
		protected global::System.Web.UI.WebControls.Label lblSecondHypenBeteenIncrementDecrementButton;
		protected global::System.Web.UI.WebControls.Button btnDecrementScoreSecondTeam;
		
		protected global::System.Web.UI.WebControls.Button btnWalkoverFirstTeam;
		protected global::System.Web.UI.WebControls.Button btnWalkoverSecondTeam;
		
		
		protected global::System.Web.UI.WebControls.Panel pnlFinishMatch;
		protected global::System.Web.UI.WebControls.Button btnFinishMatch;
		protected global::System.Web.UI.WebControls.Panel pnlWinnerName;
		protected global::System.Web.UI.WebControls.Label lblWinnerName;
		
    }
}
