//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TournamentPlanner {
    
    
    public partial class TPSuperAdmin {

		//Fields to show error messages on the page
		protected global::System.Web.UI.WebControls.Panel pnlErrorMsg;
		protected global::System.Web.UI.WebControls.Label lblErrorMsg;
		
		//Login
		protected global::System.Web.UI.WebControls.Panel pnlLogin;		
		protected global::System.Web.UI.WebControls.TextBox txtUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtOTPCode;
		protected global::System.Web.UI.WebControls.TextBox txtCaptchaCode;
		
		protected global::System.Web.UI.WebControls.Panel pnlToggleCreateTournament;
        protected global::System.Web.UI.WebControls.DropDownList ddlTournamentType;
		protected global::System.Web.UI.WebControls.TextBox txtTournamentName;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentVenue;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentEndDate;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentPOCNames;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentPOCContacts;
        protected global::System.Web.UI.WebControls.CheckBoxList cblEvents;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentOrganisation;
        protected global::System.Web.UI.WebControls.TextBox txtOranisationLogo;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentLocationAddress;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentLocationContactNos;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentEntryOpenDate;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentEntryEndDate;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentWithdrawaldate;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentDuration;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentSponsers;
        protected global::System.Web.UI.WebControls.DropDownList ddlSports;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentOwnerName;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentOwnerContactNo;
        protected global::System.Web.UI.WebControls.DropDownList ddlTournamentOwnerIDType;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentOwnerIDNo;
        protected global::System.Web.UI.WebControls.TextBox txtTournamentOwnerAddress;
        
        
        protected global::System.Web.UI.WebControls.Button btnCreateTournament;
        
        protected global::System.Web.UI.WebControls.LinkButton btnToggleCreateTournament;
        protected global::System.Web.UI.WebControls.Panel pnlCreateTournament;
        
    }
}
